CREATE TABLE comments (
    id SERIAL PRIMARY KEY,
    content TEXT NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    prototype_id INTEGER NOT NULL REFERENCES prototypes(id) ON DELETE CASCADE
);
